### ISSUE TITLE
ERROR: LoadError: UndefVarError: ffmpeg not defined

### ISSUE THREAD

**Issue by liuwa666** [JuliaIO/FFMPEG.jl#12] opened 2019-08-06 22:17 UTC
```console
julia> using FFMPEG
[ Info: Precompiling FFMPEG [c87230d0-a227-11e9-1b43-d7ebe4e7570a]
ERROR: LoadError: UndefVarError: ffmpeg not defined
Stacktrace:
 [1] top-level scope at none:0
 [2] include at .\boot.jl:326 [inlined]
 [3] include_relative(::Module, ::String) at .\loading.jl:1038
 [4] include(::Module, ::String) at .\sysimg.jl:29
 [5] top-level scope at none:2
 [6] eval at .\boot.jl:328 [inlined]
 [7] eval(::Expr) at .\client.jl:404
 [8] top-level scope at .\none:3
in expression starting at C:\Users\fuyaf\.julia\packages\FFMPEG\9JQpZ\src\FFMPEG.jl:55
ERROR: Failed to precompile FFMPEG [c87230d0-a227-11e9-1b43-d7ebe4e7570a] to C:\Users\fuyaf\.julia\compiled\v1.1\FFMPEG\TGvga.ji.
Stacktrace:
 [1] compilecache(::Base.PkgId, ::String) at .\loading.jl:1197
 [2] _require(::Base.PkgId) at .\loading.jl:960
 [3] require(::Base.PkgId) at .\loading.jl:858
 [4] require(::Module, ::Symbol) at .\loading.jl:853

(v1.1) pkg> st FFMPEG
    Status `C:\Users\fuyaf\.julia\environments\v1.1\Project.toml`
  [c87230d0] FFMPEG v0.2.2

julia> versioninfo()
Julia Version 1.1.1
Commit 55e36cc308 (2019-05-16 04:10 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\fuyaf\AppData\Local\atom\app-1.39.1\atom.exe"  -a
  JULIA_NUM_THREADS = 4

C:\Users\fuyaf> ffmpeg
ffmpeg version 3.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth --enable-libmfx
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
```

**Comment by liuwa666** [comment] 2019-08-07 00:50
@ihnorton @simonster @andreasnoack @giordano

**Comment by SimonDanisch** [comment] 2019-08-07 14:22
This is super weird, since that can only happen if build fails, but that should then error earlier... so maybe a corrupted deps file.
Anyways, that interpolation is wrong so I opened: https://github.com/JuliaIO/FFMPEG.jl/pull/13

**Comment by SimonDanisch** [comment] 2019-09-19 08:05
can you try to checkout master and run `]add FFMPEG#master; build FFMPEG; test FFMPEG` ?

**Comment by ghost** [comment] 2019-09-19 18:34
I had the same issue but this fixed it for me!

**Comment by SimonDanisch** [comment] 2019-09-20 18:47
Oh it did? :D I just figured, that I didn't fix it on master, but I think I've found the actual problem now...

**Comment by floswald** [comment] 2019-09-24 12:17
i also had problems with this. checking out master as above works for me! thanks.

**Comment by kongdd** [comment] 2019-10-01 03:48
I have the same problem. Can't solve by the above solutions

**Comment by giordano** [comment] 2019-10-01 08:20
@kongdd what operating system are you using? After checking out master, did you rebuild the package and restart julia?

**Comment by kongdd** [comment] 2019-10-01 08:54
win10 x64

**Comment by SimonDanisch** [comment] 2019-10-01 08:57
Can you post the log for `]build FFMPEG`?

**Comment by kongdd** [comment] 2019-10-01 09:07
Thanks in advance!
```
(v1.2) pkg> build FFMPEG
  Building FFMPEG → `C:\Users\kongdd\.julia\packages\FFMPEG\4fpOR\deps\build.log`
┌ Error: Error building `FFMPEG`:
│ WARNING: replacing module Anon.
│ WARNING: replacing module Anon.
│ WARNING: replacing module Anon.
│ WARNING: replacing module Anon.
│ WARNING: replacing module Anon.
│ WARNING: replacing module Anon.
│ WARNING: replacing module Anon.
│ WARNING: replacing module Anon.
│ WARNING: replacing module Anon.
│ WARNING: replacing module Anon.
│ WARNING: replacing module Anon.
│ WARNING: replacing module Anon.
│ ┌ Warning: platform_key() is deprecated, use platform_key_abi() from now on
│ │   caller = ip:0x0
│ └ @ Core :-1
│ ERROR: LoadError: LoadError: LibraryProduct(nothing, ["libavformat"], :libavformat, "Pre                                                                 fix(C:\\Users\\kongdd\\.julia\\packages\\FFMPEG\\4fpOR\\deps\\usr)") is not satisfied, can                                                                 not generate deps.jl!
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] #write_deps_file#156(::Bool, ::typeof(write_deps_file), ::String, ::Array{Product,1                                                                 }) at C:\Users\kongdd\.julia\packages\BinaryProvider\TcAwt\src\Products.jl:414
│  [3] (::getfield(BinaryProvider, Symbol("#kw##write_deps_file")))(::NamedTuple{(:verbose                                                                 ,),Tuple{Bool}}, ::typeof(write_deps_file), ::String, ::Array{Product,1}) at .\none:0
│  [4] top-level scope at C:\Users\kongdd\.julia\packages\FFMPEG\4fpOR\deps\build_FFMPEG.v                                                                 4.1.0.jl:60
│  [5] include at .\boot.jl:328 [inlined]
│  [6] include_relative(::Module, ::String) at .\loading.jl:1094
│  [7] include at .\Base.jl:31 [inlined]
│  [8] include(::String) at C:\Users\kongdd\.julia\packages\FFMPEG\4fpOR\deps\build.jl:51
│  [9] top-level scope at C:\Users\kongdd\.julia\packages\FFMPEG\4fpOR\deps\build.jl:52
│  [10] include at .\boot.jl:328 [inlined]
│  [11] include_relative(::Module, ::String) at .\loading.jl:1094
│  [12] include(::Module, ::String) at .\Base.jl:31
│  [13] include(::String) at .\client.jl:431
│  [14] top-level scope at none:5
│ in expression starting at C:\Users\kongdd\.julia\packages\FFMPEG\4fpOR\deps\build_FFMPEG                                                                 .v4.1.0.jl:60
│ in expression starting at C:\Users\kongdd\.julia\packages\FFMPEG\4fpOR\deps\build.jl:44
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\sh                                                                 are\julia\stdlib\v1.2\Pkg\src\backwards_compatible_isolation.jl:647
```

```
shell> ffmpeg
ffmpeg version N-95171-g6ca3d34ff8 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20190918
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 35.100 / 56. 35.100
  libavcodec     58. 59.101 / 58. 59.101
  libavformat    58. 33.100 / 58. 33.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 59.100 /  7. 59.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
```
```
julia> ffmpeg
ERROR: UndefVarError: ffmpeg not defined
```

**Comment by SimonDanisch** [comment] 2019-10-01 09:19
ok, can paste the output of:
```jl
using Libdl
FFMPEG = raw"C:\Users\kongdd\.julia\packages\FFMPEG\4fpOR"
bindir = joinpath(FFMPEG, "deps", "usr", "bin")
join(stdout, readdir(bindir), "\n")
Libdl.dlopen(joinpath(bindir, "avformat-58.dll"))
```

**Comment by SimonDanisch** [comment] 2019-10-01 09:20
You may need to adjust the names / paths, I'm not on windows atm, so couldn't actually run this ;)
@giordano, is there an easy way to do your magic to figure out what avformat is missing?

**Comment by kongdd** [comment] 2019-10-01 09:35
```
julia> join(stdout, readdir(bindir), "\n")
avcodec-58.dll
avcodec.lib
avdevice-58.dll
avdevice.lib
avfilter-7.dll
avfilter.lib
avformat-58.dll
avformat.lib
avresample-4.dll
avresample.lib
avutil-56.dll
avutil.lib
bunzip2
bzcat
bzcmp
bzdiff
bzegrep
bzfgrep
bzgrep
bzip2
bzip2recover
bzless
bzmore
ffmpeg.exe
ffprobe.exe
fribidi.exe
lame.exe
libass-9.dll
libbz2-1.dll
libbz2.dll
libfdk-aac-1.dll
libfreetype-6.dll
libfribidi-0.dll
libmp3lame-0.dll
libogg-0.dll
libvorbis-0.dll
libvorbisenc-2.dll
libvorbisfile-3.dll
libz-1.2.11.dll
libz-1.dll
libz.dll
postproc-55.dll
postproc.lib
swresample-3.dll
swresample.lib
swscale-5.dll
swscale.lib
x264.exe
x265.exe

julia> Libdl.dlopen(joinpath(bindir, "avformat-58.dll"))
Ptr{Nothing} @0x00007ff886ba0000
```

**Comment by asgherali39** [comment] 2019-10-01 13:09
Hi @SimonDanisch  and @giordano

I have exactly the same issue. I followed the instructions that you give in this thread and I get the same output as above. Can you please tell me whats missing? Thanks

**Comment by giordano** [comment] 2019-10-01 13:15
Honestly I'm a bit lost.  The output
```julia
julia> Libdl.dlopen(joinpath(bindir, "avformat-58.dll"))
Ptr{Nothing} @0x00007ff886ba0000
```
indicates that the library could be opened (otherwise you would get an error message), so I don't understand what's the problem when building the package

**Comment by SimonDanisch** [comment] 2019-10-01 13:33
Can you try all of them?
```
libs = [
"avcodec-58.dll",
"avformat-58.dll",
"avutil-56.dll",
"swscale-5.dll",
"avfilter-7.dll",
"avdevice-58.dll"
]
for lib in libs
    Libdl.dlopen(joinpath(bindir, lib))
end
```
@staticfloat what other things can lead to a LibraryProduct being unsatisfied?

**Comment by staticfloat** [comment] 2019-10-01 17:28
Can someone who can reproduce this issue please modify their `deps/build_FFMPEG.v4.1.0.jl` file and set `const verbose = true` at the top, then re-run the `build`?

**Comment by giordano** [comment] 2019-10-01 18:45
Another request for those who are experiencing the issue: in a clean Julia session please run
```julia
using Libdl
Libdl.dllist()
```
and paste the output here

**Comment by asgherali39** [comment] 2019-10-02 05:53
I get the following output by trying what you suggest. 

ERROR: could not load library "C:\Users\Asgher Ali\.julia\packages\FFMPEG\4fpOR\deps\usr\bin\avfilter-7.dll"
The specified module could not be found.

Stacktrace:
 [1] #dlopen#3(::Bool, ::Function, ::String, ::UInt32) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Libdl\src\Libdl.jl:109
 [2] dlopen at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Libdl\src\Libdl.jl:109 [inlined] (repeats 2 times)
 [3] top-level scope at .\REPL[16]:2 [inlined]
 [4] top-level scope at .\none:0

**Comment by giordano** [comment] 2019-10-02 21:58
@asgherali39 @kongdd  Could you please try installing my fork and see if this fixes the issue for you?
```julia
]add https://github.com/giordano/FFMPEG.jl#tmp
```

**Comment by asgherali39** [comment] 2019-10-03 07:03
julia> using Libdl

julia> Libdl.dllist()
62-element Array{AbstractString,1}:
 "C:\\Users\\Asgher Ali\\AppData\\Local\\Julia-1.1.1\\bin\\julia.exe"
 "C:\\WINDOWS\\SYSTEM32\\ntdll.dll"
 "C:\\WINDOWS\\System32\\KERNEL32.DLL"
 "C:\\WINDOWS\\System32\\KERNELBASE.dll"
 "C:\\WINDOWS\\System32\\msvcrt.dll"
 "C:\\WINDOWS\\System32\\USER32.dll"
 "C:\\WINDOWS\\System32\\win32u.dll"
 "C:\\WINDOWS\\System32\\GDI32.dll"
 "C:\\WINDOWS\\System32\\gdi32full.dll"
 "C:\\WINDOWS\\System32\\msvcp_win.dll"
 "C:\\WINDOWS\\System32\\ucrtbase.dll"
 "C:\\Users\\Asgher Ali\\AppData\\Local\\Julia-1.1.1\\bin\\libgcc_s_seh-1.dll"
 "C:\\Users\\Asgher Ali\\AppData\\Local\\Julia-1.1.1\\bin\\libwinpthread-1.dll"
 ⋮
 "C:\\Users\\Asgher Ali\\AppData\\Local\\Julia-1.1.1\\bin\\libmpfr.DLL"
 "C:\\Users\\Asgher Ali\\AppData\\Local\\Julia-1.1.1\\bin\\libdSFMT.DLL"
 "C:\\Users\\Asgher Ali\\AppData\\Local\\Julia-1.1.1\\bin\\libopenblas64_.DLL"
 "C:\\Users\\Asgher Ali\\AppData\\Local\\Julia-1.1.1\\bin\\libgfortran-4.dll"
 "C:\\Users\\Asgher Ali\\AppData\\Local\\Julia-1.1.1\\bin\\libquadmath-0.dll"
 "C:\\Users\\Asgher Ali\\AppData\\Local\\Julia-1.1.1\\bin\\libcholmod.DLL"
 "C:\\Users\\Asgher Ali\\AppData\\Local\\Julia-1.1.1\\bin\\libccolamd.dll"
 "C:\\Users\\Asgher Ali\\AppData\\Local\\Julia-1.1.1\\bin\\libsuitesparseconfig.dll"
 "C:\\Users\\Asgher Ali\\AppData\\Local\\Julia-1.1.1\\bin\\libcamd.dll"
 "C:\\Users\\Asgher Ali\\AppData\\Local\\Julia-1.1.1\\bin\\libamd.dll"
 "C:\\Users\\Asgher Ali\\AppData\\Local\\Julia-1.1.1\\bin\\libcolamd.dll"
 "C:\\Users\\Asgher Ali\\AppData\\Local\\Julia-1.1.1\\bin\\libsuitesparse_wrapper.DLL"

julia>

**Comment by kongdd** [comment] 2019-10-05 01:35
still not work. I think if FFMPEG.jl could pass the test on `appveyor`, the error will be gone.

**Comment by giordano** [comment] 2019-10-05 07:20
> still not work

What did you exactly?

>  I think if FFMPEG.jl could pass the test on appveyor, the error will be gone.

The package never had problems on AppVeyor. Instead Travis has an incomplete installation of Windows: https://travis-ci.community/t/any-chance-of-providing-an-environment-with-desktop-experience/1024  Most of the developers of this package don't have Windows and who has Windows cannot reproduce the error. We need collaboration from you to understand what's going on.

**Comment by kongdd** [comment] 2019-10-05 10:47
Hi @giordano 

The reality is that it failed on AppVeyor, https://ci.appveyor.com/project/kongdd/ffmpeg-jl/builds/27899603/job/1ymn6ihm2gmsveur.
The exactly same error I faced.

I forked this repo just now. Except for README.md, nothing modified.

**Comment by giordano** [comment] 2019-10-05 11:04
I was not aware that the latest version of master was failing, all other commits that I can see here https://github.com/JuliaIO/FFMPEG.jl/commits/master are passing tests on AppVeyor.

Anyway, three days ago I asked you guys to try my fork and see if it works for you:
```julia
]add https://github.com/giordano/FFMPEG.jl#tmp
```
Tests are passing on AppVeyor: https://ci.appveyor.com/project/giordano/ffmpeg-jl/builds/27899739, but none of you gave me a feedback.  We're doing our best to fix this issue, but I'd appreciate a bit more of collaboration.

**Comment by kongdd** [comment] 2019-10-05 11:23
I am sorry for the later response. Thanks for your work

**Comment by giordano** [comment] 2019-10-05 15:59
I still don't know if this works for you 🙂

**Comment by dubik** [comment] 2019-10-05 16:19
> @asgherali39 @kongdd Could you please try installing my fork and see if this fixes the issue for you?
> 
> ```julia
> ]add https://github.com/giordano/FFMPEG.jl#tmp
> ```

@giordano It worked for me. I had exactly same issues on Windows 10 with Julia 1.2 (couldn't load libavformat).
```
(v1.2) pkg> add https://github.com/giordano/FFMPEG.jl
   Cloning git-repo `https://github.com/giordano/FFMPEG.jl`
  Updating git-repo `https://github.com/giordano/FFMPEG.jl`
  Updating git-repo `https://github.com/giordano/FFMPEG.jl`
 Resolving package versions...
  Updating `C:\Users\sergi\.julia\environments\v1.2\Project.toml`
  [c87230d0] ↓ FFMPEG v0.2.3 #master (https://github.com/JuliaIO/FFMPEG.jl.git) ⇒ v0.2.0 #master (https://github.com/giordano/FFMPEG.jl)
  Updating `C:\Users\sergi\.julia\environments\v1.2\Manifest.toml`
  [c87230d0] ↓ FFMPEG v0.2.3 #master (https://github.com/JuliaIO/FFMPEG.jl.git) ⇒ v0.2.0 #master (https://github.com/giordano/FFMPEG.jl)
  Building FFMPEG → `C:\Users\sergi\.julia\packages\FFMPEG\aEyFi\deps\build.log`

(v1.2) pkg>                                                                                                            ```

**Comment by giordano** [comment] 2019-10-05 16:23
Great, thank you so much for the feedback! I had opened a pull request for FFMPEGBuilder: https://github.com/JuliaIO/FFMPEGBuilder/pull/7. Hopefully the fix will go live in the official FFMPEG.jl soon, for the time being you can use my temporary branch.

**Comment by kongdd** [comment] 2019-10-06 01:52
Hi @giordano, 
I also succeed to build FFMPEG. 
I need to clarify that I am glad to feedback in real-time. But FFMPEG have so many dependencies. Github is a tortoise in China. Downloading those dependencies will cost me few hours. Each time, it will cost a few hours or interrupted by downloading errors. But finally succeed.

It will be great if julia has compiled binary packages (just like R language).

**Comment by asgherali39** [comment] 2019-10-06 10:42
Hi @giordano 

I also succeed to build FFMPEG. I am really sorry for being late responding to your instructions. Thanks for the help.

**Comment by sbulcsu** [comment] 2019-10-07 18:33
Hi @giordano,
Your tmp branch also worked for me. Ubuntu 18.04, Julia v1.2. It took me a while to find your proposal as a solution. Thanks a lot!

**Comment by giordano** [comment] 2019-10-07 18:54
Wait, what? My branch works at all on Linux? I'm pretty sure that it shouldn't 😕

**Comment by mmattocks** [comment] 2019-10-07 18:55
> Wait, what? My branch works at all on Linux? I'm pretty sure that it shouldn't confused

It doesn't work for me on Linux Mint 19.2 FWIW. I am also getting the OP's error, though, which is currently breaking Plots.jl on Julia 1.2.

**Comment by giordano** [comment] 2019-10-07 19:03
Could you please open a new issue and describe your problem? The one in this ticket is very Windows-specific, and also the fix contained in my branch is extremely Windows-specific.

**Comment by mmattocks** [comment] 2019-10-07 19:37
> Could you please open a new issue and describe your problem? The one in this ticket is very Windows-specific, and also the fix contained in my branch is extremely Windows-specific.

Apologies; my issue is addressed by this pull issue here: https://github.com/JuliaIO/FFMPEG.jl/pull/13

There is an unescaped interpolator at FFMPEG.jl line 55, as referenced by OP's error. I have no idea if there is some additional problem with windows, but that particular error is addressed by escaping the $.

**Comment by sbulcsu** [comment] 2019-10-10 08:12
> Wait, what? My branch works at all on Linux? I'm pretty sure that it shouldn't

@giordano:
Yes, it worked for me. I didn't notice that this is a Windows specific issue, so I tried your 

```]add https://github.com/giordano/FFMPEG.jl#tmp```

which worked on my Ubuntu 18.04 system with Julia 1.2. Bit confused now...
Previously the Plots.jl installation stopped at the same step as for the others,  at FFMPEG.

**Comment by hesampour** [comment] 2019-10-15 06:00
From C://users/your UserName completely remove .julia folder and then uninstall julia and reinstall it agin solve the problem

**Closed as completed** 2019-11-27 10:21 UTC
